- name: Setup Node.js
  uses: actions/setup-node@v3
  with:
    node-version: 18

- name: Install deps
  run: |
    cd app
    npm install

- name: Build & export
  run: |
    cd app
    npm run build
    npm run export

- name: Deploy to Firebase
  uses: FirebaseExtended/action-hosting-deploy@v0
  with:
    repoToken: "${{ secrets.GITHUB_TOKEN }}"
    firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
    channelId: live
    projectId: your-firebase-project-id
